"""
alert_generator.py — PineScript v6 code generator for Lighthouse alerts.

Generates a complete Pine Script v6 strategy that:
* Implements the Gaussian Channel L+S strategy (matching gaussian_channel.py)
* Emits Signum v2 compatible JSON alerts to the Lighthouse webhook
* Includes alertcondition() calls (for TradingView alert setup UI)
* Includes alert() calls (fired automatically on bar close)

Usage
-----
    from app.pinescript.alert_generator import AlertGenerator

    gen = AlertGenerator(params={"period": 100, "poles": 3})
    code = gen.generate(bot_id="my-webhook-secret")
    print(code)

    # Or save to file:
    gen.save("pinescripts/my_strategy.pine", bot_id="my-webhook-secret")
"""

from __future__ import annotations

import os
from typing import Any, Dict, Optional


# Default parameters matching GaussianChannelStrategy.default_params
_DEFAULT_PARAMS: Dict[str, Any] = {
    "period":              100,
    "poles":               3,
    "multiplier":          2.0,
    "atr_period":          14,
    "use_macd":            False,
    "macd_fast":           12,
    "macd_slow":           26,
    "macd_signal":         9,
    "sl_pct":              5.0,    # stored as percent (5.0 = 5%)
    "tp_pct":              0.0,
    "use_time_filter":     False,
    "trade_hours_start":   1,
    "trade_hours_end":     23,
}


class AlertGenerator:
    """Generate PineScript v6 code for the Gaussian Channel L+S strategy."""

    def __init__(self, params: Optional[Dict[str, Any]] = None) -> None:
        self.params: Dict[str, Any] = {**_DEFAULT_PARAMS, **(params or {})}

    def generate(self, bot_id: str) -> str:
        """Return a complete PineScript v6 strategy string.

        Parameters
        ----------
        bot_id : str
            The Lighthouse webhook secret / bot ID.  Hard-coded in the
            generated alert JSON messages so TradingView sends it verbatim.

        Returns
        -------
        str
            Full PineScript v6 source code.
        """
        p = self.params
        sl_pct_disp         = float(p["sl_pct"])
        tp_pct_disp         = float(p["tp_pct"])
        use_macd_str        = "true" if p["use_macd"]        else "false"
        use_time_filter_str = "true" if p["use_time_filter"] else "false"

        # TradingView template variables that Pine Script alert() messages
        # support.  Stored as plain Python strings so we can format them
        # into the output without the f-string engine misinterpreting them.
        tv_timenow = "{{timenow}}"
        tv_ticker  = "{{ticker}}"
        tv_close   = "{{close}}"

        # Alert JSON payloads — built with .format() (no f-string) so that
        # the double-brace TradingView placeholders are preserved literally.
        buy_json = (
            '{{"schema":"2","bot_id":"{bid}",'
            '"timestamp":"{ts}","ticker":"{tick}",'
            '"action":"buy","price":{price},"position_size":100}}'
        ).format(bid=bot_id, ts=tv_timenow, tick=tv_ticker, price=tv_close)

        sell_json = (
            '{{"schema":"2","bot_id":"{bid}",'
            '"timestamp":"{ts}","ticker":"{tick}",'
            '"action":"sell","price":{price},"position_size":-100}}'
        ).format(bid=bot_id, ts=tv_timenow, tick=tv_ticker, price=tv_close)

        close_json = (
            '{{"schema":"2","bot_id":"{bid}",'
            '"timestamp":"{ts}","ticker":"{tick}",'
            '"action":"sell","price":{price},"position_size":0}}'
        ).format(bid=bot_id, ts=tv_timenow, tick=tv_ticker, price=tv_close)

        # Build the Pine Script source with safe string concatenation.
        # Only Python variables that contain no braces reach the f-string.
        parts = [
            "//@version=6",
            "// " + "─" * 77,
            "// Gaussian Channel L+S v6 — Lighthouse Alerts",
            "// Generated by Lighthouse Trading AlertGenerator",
            "// Strategy logic mirrors backtester/strategies/gaussian_channel.py",
            "//",
            "// Setup:",
            "//   1. Paste this script into TradingView Pine Editor as a Strategy.",
            "//   2. The bot_id_val variable is pre-filled with your webhook secret.",
            "//   3. Create TradingView alerts from the alertcondition() triggers.",
            "//   4. Set the alert webhook URL to https://your-server/webhook/<uuid>.",
            "// " + "─" * 77,
            "",
            "strategy(",
            '    title             = "Gaussian Channel L+S v6 — Lighthouse Alerts",',
            "    overlay           = true,",
            "    default_qty_type  = strategy.percent_of_equity,",
            "    default_qty_value = 100,",
            "    initial_capital   = 10000,",
            "    commission_type   = strategy.commission.percent,",
            "    commission_value  = 0.05",
            ")",
            "",
            "// ── Inputs ───────────────────────────────────────────────────────────────────",
            f'bot_id_val   = "{bot_id}"',
            f'period       = input.int({p["period"]},        "Gaussian Period", minval=2, maxval=500)',
            f'poles        = input.int({p["poles"]},         "Poles",           minval=1, maxval=4)',
            f'multiplier   = input.float({p["multiplier"]:.1f}, "ATR Multiplier", minval=0.1, step=0.1)',
            f'atr_period   = input.int({p["atr_period"]},   "ATR Period",      minval=1)',
            f'sl_pct       = input.float({sl_pct_disp:.1f}, "Stop-Loss %",     minval=0.0, step=0.1)',
            f'tp_pct       = input.float({tp_pct_disp:.1f}, "Take-Profit %",   minval=0.0, step=0.1)',
            f'use_macd     = input.bool({use_macd_str},     "Use MACD Filter")',
            f'macd_fast    = input.int({p["macd_fast"]},    "MACD Fast",  minval=1, group="MACD")',
            f'macd_slow    = input.int({p["macd_slow"]},    "MACD Slow",  minval=1, group="MACD")',
            f'macd_sig     = input.int({p["macd_signal"]},  "MACD Signal",minval=1, group="MACD")',
            f'use_tf       = input.bool({use_time_filter_str}, "Time Filter", group="Time Filter")',
            f'tf_start     = input.int({p["trade_hours_start"]}, "Start Hour (UTC)",'
            f' minval=0, maxval=23, group="Time Filter")',
            f'tf_end       = input.int({p["trade_hours_end"]},   "End Hour (UTC)",'
            f'   minval=0, maxval=23, group="Time Filter")',
            "",
            "// ── Gaussian IIR Filter (Ehlers multi-pole) ──────────────────────────────────",
            "//   Matches the _gaussian_filter() function in gaussian_channel.py",
            "gaussianFilter(src, len, p) =>",
            "    beta  = (1 - math.cos(2 * math.pi / len)) / (math.pow(2, 1.0 / p) - 1)",
            "    alpha = math.min(-beta + math.sqrt(beta * beta + 2 * beta), 1.0)",
            "    var float f1 = na",
            "    var float f2 = na",
            "    var float f3 = na",
            "    var float f4 = na",
            "    f1 := alpha * src + (1 - alpha) * nz(f1[1], src)",
            "    f2 := p >= 2 ? alpha * f1 + (1 - alpha) * nz(f2[1], f1) : f1",
            "    f3 := p >= 3 ? alpha * f2 + (1 - alpha) * nz(f3[1], f2) : f2",
            "    f4 := p >= 4 ? alpha * f3 + (1 - alpha) * nz(f4[1], f3) : f3",
            "    p == 1 ? f1 : p == 2 ? f2 : p == 3 ? f3 : f4",
            "",
            "// ── Indicators ───────────────────────────────────────────────────────────────",
            "gauss   = gaussianFilter(close, period, poles)",
            "atr_val = ta.atr(atr_period)",
            "upper   = gauss + multiplier * atr_val",
            "lower   = gauss - multiplier * atr_val",
            "",
            "// ── Band states ───────────────────────────────────────────────────────────────",
            "above_upper = close > upper",
            "below_lower = close < lower",
            "",
            "cross_above_upper = above_upper  and not above_upper[1]   // just crossed above",
            "cross_below_lower = below_lower  and not below_lower[1]   // just crossed below",
            "recross_upper     = not above_upper and above_upper[1]    // left upper band",
            "recross_lower     = not below_lower and below_lower[1]    // left lower band",
            "",
            "// ── Optional MACD Filter ──────────────────────────────────────────────────────",
            "[_, _, hist]  = ta.macd(close, macd_fast, macd_slow, macd_sig)",
            "macd_bullish  = hist > 0",
            "",
            "// ── Time Filter ───────────────────────────────────────────────────────────────",
            "in_time = not use_tf or (hour >= tf_start and hour < tf_end)",
            "",
            "// ── Signal conditions ─────────────────────────────────────────────────────────",
            "long_cond  = cross_above_upper and in_time and (not use_macd or macd_bullish)",
            "short_cond = cross_below_lower and in_time and (not use_macd or not macd_bullish)",
            "close_long  = recross_upper",
            "close_short = recross_lower",
            "",
            "// ── Strategy entries ──────────────────────────────────────────────────────────",
            "if long_cond",
            '    strategy.entry("Long", strategy.long)',
            "    if sl_pct > 0",
            '        strategy.exit("Long SL/TP", "Long",',
            "            stop   = close * (1 - sl_pct / 100),",
            "            limit  = tp_pct > 0 ? close * (1 + tp_pct / 100) : na)",
            "",
            "if short_cond",
            '    strategy.entry("Short", strategy.short)',
            "    if sl_pct > 0",
            '        strategy.exit("Short SL/TP", "Short",',
            "            stop   = close * (1 + sl_pct / 100),",
            "            limit  = tp_pct > 0 ? close * (1 - tp_pct / 100) : na)",
            "",
            "if close_long",
            '    strategy.close("Long", comment="price_left_upper_band")',
            "",
            "if close_short",
            '    strategy.close("Short", comment="price_left_lower_band")',
            "",
            "// ── Alert JSON payloads (Signum v2 / Lighthouse format) ───────────────────────",
            "//   TradingView substitutes {{timenow}}, {{ticker}}, {{close}} at fire time.",
            "//   bot_id is hard-coded at generation time.",
            f"buy_msg   = '{buy_json}'",
            f"sell_msg  = '{sell_json}'",
            f"close_msg = '{close_json}'",
            "",
            "// ── alertcondition() — set up alerts manually in the TradingView UI ───────────",
            'alertcondition(long_cond,                 "Long Entry",      buy_msg)',
            'alertcondition(short_cond,                "Short Entry",     sell_msg)',
            'alertcondition(close_long or close_short, "Close Position",  close_msg)',
            "",
            "// ── alert() — fires automatically on bar close ────────────────────────────────",
            "if long_cond",
            "    alert(buy_msg, alert.freq_once_per_bar)",
            "",
            "if short_cond",
            "    alert(sell_msg, alert.freq_once_per_bar)",
            "",
            "if close_long",
            "    alert(close_msg, alert.freq_once_per_bar)",
            "",
            "if close_short",
            "    alert(close_msg, alert.freq_once_per_bar)",
            "",
            "// ── Plots ─────────────────────────────────────────────────────────────────────",
            'plot(gauss, "Gaussian Center", color=color.yellow,    linewidth=2)',
            'plot(upper, "Upper Band",      color=color.new(color.green, 20), linewidth=1)',
            'plot(lower, "Lower Band",      color=color.new(color.red,   20), linewidth=1)',
            "",
            'bgcolor(long_cond  ? color.new(color.green, 85) : na, title="Long signal")',
            'bgcolor(short_cond ? color.new(color.red,   85) : na, title="Short signal")',
            "",
        ]
        return "\n".join(parts)

    def save(self, path: str, bot_id: str) -> None:
        """Write the generated PineScript to *path*.

        Creates parent directories as needed.

        Parameters
        ----------
        path : str
            File path to write (e.g. ``"pinescripts/my_bot.pine"``).
        bot_id : str
            Bot ID / webhook secret embedded in the generated code.
        """
        os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
        code = self.generate(bot_id)
        with open(path, "w") as fh:
            fh.write(code)
